### ISSUE TITLE
Create a time from epoch converter

### ISSUE THREAD

**Issue by THHamiltonSmith** [THHamiltonSmith/webdevhub#2]
A feature to convert an epoch time to a readable date and vice-versa.

**Comment by PranavThampi** [comment]
Hey @THHamiltonSmith, I'd like to take a crack at it.

**Comment by THHamiltonSmith** [comment]
@PranavThampi sounds great! Let me know if you have any questions.

**Comment by PranavThampi** [comment]
Hey @THHamiltonSmith, Could you please guide me as to how can I use the Luna framework CSS? I tried using the class mentioned on their [website](https://designbycode.github.io/Luna/Build/components.html#forms)

**Comment by THHamiltonSmith** [comment]
@PranavThampi The Luna framework is just a small CSS library I am working on that I am testing out on WebDevHub. The Luna framework you linked is a different one, I didn't even know it existed!

If you need to you can modify the code inside the `luna-framework.css` file, but you shouldn't need too. You should be able to add any custom styling you need in the `style.css` file. The whole CSS situation is a bit messy at the moment, so I am working on cleaning it up, and when I do it will a bit easier to understand and manage. Sorry for the confusion!

**Comment by PranavThampi** [comment]
Adding a framework like Bootstrap might help a lot

**Comment by PranavThampi** [comment]
Can I use bootstrap or something. I'll be using it by calling the script in the html instead of installing the package.

**Comment by THHamiltonSmith** [comment]
@PranavThampi Sure. The only problem is that bootstrap may play around with some of the other styling and throw some things out of proportion. If you can get it to work though, then that's great.

**Comment by PranavThampi** [comment]
@THHamiltonSmith  I have created a [pull request](https://github.com/THHamiltonSmith/webdevhub/pull/22) for the same. Kindly review
