### ISSUE TITLE
Incorrect reading and speaking times in word-counter for huge paragraphs.

### ISSUE THREAD

**Issue by satyagalla** [THHamiltonSmith/webdevhub#7]
Fix the minutes and show the correct time.

![Screenshot (39) 1](https://user-images.githubusercontent.com/76934078/176119953-c4574431-84fd-4a6c-abcc-ed3b8ef649e2.png)

**Comment by satyagalla** [comment]
Found this while I was playing around :)

**Comment by THHamiltonSmith** [comment]
Solved in the latest commit, just forgot to divide this line `var minutes = Math.round(readingTimeSeconds - hours * 3600);` by 60 so it wouldn't add the hours and minutes correctly for large times. Should work now.
